spring.application.name=nestfinder

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/nestfinder
spring.datasource.username=root
spring.datasource.password=Sumit@2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

jwt.secret=3T7R3vudc7v0N0o6AjlA57kqv6OklWgqg4XbJswYFjBqX9PGiX0Zw3ZcPf3sPiL8vB2J0KzT6F6x9X7hQzZb6Q==
jwt.expirationMs=86400000